#pragma once

typedef struct {
	int id;
	int width;
	int height;
	int format
	int bpp;
	int rotation; // ooo fancy
	void * fb;
} display_t;

enum {
	DISPLAY_FMT_RGB2,
	DISPLAY_FMT_RGB4,
	DISPLAY_FMT_RGB8,
	DISPLAY_FMT_RGB15,
	DISPLAY_FMT_RGB16,
	DISPLAY_FMT_RGB18,
	DISPLAY_FMT_RGB19,
	DISPLAY_FMT_RGB24,
	DISPLAY_FMT_RGB25,
	DISPLAY_FMT_RGB30,
	DISPLAY_FMT_RGBA32,
	DISPLAY_FMT_RGB36,
	DISPLAY_FMT_RGB40,
	DISPLAY_FMT_RGB48,
	DISPLAY_FMT_RGB54,
	DISPLAY_FMT_RGB59,
	DISPLAY_FMT_RGB72,
	DISPLAY_FMT_RGB75,
	DISPLAY_FMT_RGB96,

	// fancy HDR / high precision RGB formats
	DISPLAY_FMT_HDR30, // HDR
	DISPLAY_FMT_HDRA40, // HDR
	DISPLAY_FMT_RGBE32, // Radiance HDR
	DISPLAY_FMT_HDR36, // Dolby Vision
	DISPLAY_FMT_HDR48, // Super HDR
	DISPLAY_FMT_HDR96, // float3

	DISPLAY_FMT_MONO1,
	DISPLAY_FMT_MONO2,
	DISPLAY_FMT_MONO4,
	DISPLAY_FMT_MONO8,
	DISPLAY_FMT_MONO15,
	DISPLAY_FMT_MONO16,
	DISPLAY_FMT_MONO18,
	DISPLAY_FMT_MONO24,
	DISPLAY_FMT_MONO32,

	DISPLAY_FMT_PAL1, // this format has probably *never* been used on systems that support it
	DISPLAY_FMT_PAL2,
	DISPLAY_FMT_PAL4,
	DISPLAY_FMT_PAL8,
	DISPLAY_FMT_PAL16,

	DISPLAY_FMT_TEXT,
};
